# Generated by Django 4.2.7 on 2023-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_review_brew_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(max_length=100),
        ),
    ]
